server:
  port: 8083
spring:
  application:
    name: clothing
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: root
    url: jdbc:sqlserver://localhost:1433;databaseName=m2m_clothing;encrypt=false;trustServerCertificate=true;
    username: sa
  mail:
    host: smtp.gmail.com
    password: oanxsumpkcoisyrx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: kaisamaslain+Nerdyers@gmail.com
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 321877704749-2v71bd2jvjvhg1qs8ntnlokcbv3qb4el.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  mvc:
    cors:
      allowed-methods: GET,POST,PUT,DELETE
      allowed-origins: '*'
  web:
    resources:
      static-locations: classpath:/templates/swappa, classpath:/templates/swappa/media
paypal:
  client-id: AUn8UV5sTafGqBu9Y6BAB9DKZlgUDgy534_sHcoYwifxkvIZsbpNfIjP0zU3H8u8XJEWTiw8UuzatRZC
  client-secret: ECNMSzeMKvjXkOBdYZ6Vw9SJ6tXJXel8tcBrk6ISBi_pXLxKJxoiq6Uj4dWybRoQTDBaIOamuknc-9sR
  mode: sandbox # 'sandbox' for testing; 'live' for real production